export enum Configuration {
  PORT = 'PORT',
  HOST = 'HOST',
  SUPERUSER = 'SUPERUSER',
  USERNAME = 'USERNAME',
  PASSWORD = 'PASSWORD',
  DATABASE = 'DATABASE',
  JWT_SECRET = 'JWT_SECRET',
  API_SENDGRID = 'API_SENDGRID',
  PASS_SENDGRID = 'PASS_SENDGRID',
  URL_FRONTEND = 'URL_FRONTEND',
}
